[paris]
web_paris ansible_host=192.168.1.127 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[abidjan]
web_abidjan ansible_host=3.252.52.40 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[monitoring]
zabbix_server ansible_host=4.223.71.179 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'